# Generated by Django 4.1.2 on 2023-03-13 13:35

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_blogindexpage_blogpage_homepage_body_blogpageauthor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="feed_image",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="private_field",
        ),
        migrations.AddField(
            model_name="blogpage",
            name="intro",
            field=models.CharField(default="intro", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
